spring:
  application:
    name: com.amido.stacks-api-cqrs-events
  data:
    rest:
      detection-strategy: annotated

server:
  # Note: ONLY use this if you're behind a trusted Reverse Proxy, such as Application Gateway.
  # If you host this app directly then users can easily inject headers.
  forward-headers-strategy: framework
  #######
  port: 9000

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, beans

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    display-operation-id: true
    # TODO: Swagger keeps redirecting, it'd be good to stop it if possible
    path: /swagger/index.html
  packagesToScan: com.amido.stacks
  api-docs:
    groups:
      enabled: true
    enabled: true
    path: /swagger/oas-json

azure:
  cosmos:
    uri: https://192.168.50.169:8081
    database: Stacks
    key: ${COSMOSDB_KEY}
  application-insights:
    instrumentation-key: xxxxxx
    enabled: true
  keyvault:
    enabled: false
    uri: https://amido-com.amido.stacks-tmp.vault.azure.net/
    client-id: xxxxxx
    client-key: xxxxxx
    tenant-id: xxxxxx
  servicebus:
    connectionString: ${SB_CONNECTION_STRING}
    topicName: ${SB_TOPIC}
    subscriptionName: ${SB_SUBSCRIPTION}
    enabled: ${SB_ENABLED:false}

auth:
  #Config switch to enable (true) or disable(false) Auth0.Provide either true or false to enable or disable
  isEnabled: true
  resource:
    url: https://amidostacks.eu.auth0.com/oauth/tokenLocal
  token:
    url: /v1/tokenLocal
  #The issuer of the JWT Token. Typically, this is your Auth0 domain with an https://
  issuer:
    https: //amidostacks.eu.auth0.com/Local
  #The unique identifier for your API
  apiAudience: https://amidostacks.eu.auth0.com/api/v2/Local

api:
  endpoints:
    v1:
      url: /v1/menu/**
      endpoint: /v1/menu
      privateEndpoint: false

    v2:
      url: /v2/menu/**
      endpoint: /v2/menu
      privateEndpoint: true
      